stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "syslog-alpine"
  IMAGE_TAG: "latest"
  GITHUB_PROJECT: "p42/syslog-alpine-docker.git"

before_script:
  - docker info

build-master:
  tags:
    - docker
  stage: build
  script:
    - git checkout master
    - docker build --pull -t "${IMAGE_NAME}:latest" .
  only:
    - master

build:
  tags:
    - docker
  stage: build
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - docker build --pull -t "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" .
  except:
    - master

test-master:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:latest" /ci_tests/run_tests system
  only:
    - master

test:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" /ci_tests/run_tests system
  except:
    - master

deploy_to_github-master:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout master
    - git push git@github.com:${GITHUB_PROJECT} master
  only:
    - master

deploy_to_github:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME}
  except:
    - master

deploy_tags_to_github:
  tags:
    - docker
    - github-key
  stage: deploy
  script:
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push git@github.com:${GITHUB_PROJECT} ${CI_COMMIT_REF_NAME} --tags
  only:
    - tags
